name: rainfall-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pandas>=2.2
  - dash>=2.16
  - dash-bootstrap-components>=1.6
  - dash-bootstrap-templates>=1.1
  - plotly>=5.19
  - statsmodels>=0.14
  - python-box>=7.1
  - pyyaml>=6.0
  - pip
  - pip:
    - hidrokit==0.5
